"use client";

export default function GlobalError({ error, retry }: { error: Error & { digest?: string }; retry: () => void }) {
  return <html lang="es"><head><title>Moneva · Error temporal</title><style>{`
    :root{color-scheme:light;--bg:#f8f6f0;--fg:#18221d;--muted:#69736d;--line:#d8ddd8;--primary:#26765d;--soft:#e4f1eb}
    *{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
    .stage{position:relative;display:flex;min-height:100dvh;overflow:hidden;padding:20px}.stage:before{content:"";position:absolute;inset:0;background-image:linear-gradient(to right,rgba(100,112,104,.12) 1px,transparent 1px),linear-gradient(to bottom,rgba(100,112,104,.09) 1px,transparent 1px);background-size:72px 72px;mask-image:linear-gradient(to bottom,#000,transparent 78%)}
    .wrap{position:relative;display:flex;min-height:calc(100dvh - 40px);width:min(100%,1440px);margin:auto;flex-direction:column}.brand{display:flex;min-height:56px;align-items:center;gap:10px;border-bottom:1px solid var(--line);font-size:15px;font-weight:700;letter-spacing:-.02em}.mark{position:relative;display:inline-block;width:32px;height:32px}.mark:before,.mark:after{content:"";position:absolute;top:6px;width:7px;height:20px;border-radius:2px;background:var(--primary)}.mark:before{left:6px;transform:skewX(-18deg)}.mark:after{right:6px;transform:skewX(18deg);opacity:.55}.mark i{position:absolute;bottom:6px;left:8px;width:16px;height:5px;border-radius:99px;background:var(--primary)}
    .content{display:grid;flex:1;align-content:center;gap:34px;padding:48px 0}.lead{max-width:760px}.eyebrow{margin:0;color:var(--primary);font-size:11px;font-weight:800;letter-spacing:.15em;text-transform:uppercase}.lead h1{max-width:13ch;margin:18px 0 0;font-size:clamp(38px,6vw,72px);font-weight:600;line-height:1.01;letter-spacing:-.055em}.lead p{max-width:660px;margin:20px 0 0;color:var(--muted);font-size:16px;line-height:1.75}.action{max-width:520px;border-top:1px solid var(--line);border-bottom:1px solid var(--line);padding:28px 0}.action h2{margin:0;font-size:26px;line-height:1.15;letter-spacing:-.035em}.action p{margin:12px 0 0;color:var(--muted);font-size:14px;line-height:1.65}.action button{min-height:48px;width:100%;margin-top:24px;border:0;border-radius:999px;background:var(--primary);color:#fff;padding:0 22px;font:inherit;font-size:14px;font-weight:750;cursor:pointer}.action button:focus-visible{outline:3px solid color-mix(in srgb,var(--primary),transparent 55%);outline-offset:3px}.ref{font-size:11px!important}.foot{display:flex;min-height:48px;align-items:center;justify-content:space-between;gap:12px;border-top:1px solid var(--line);color:var(--muted);font-size:11px}
    @media(min-width:900px){.stage{padding:20px 48px}.wrap{min-height:calc(100dvh - 40px)}.content{grid-template-columns:minmax(0,1fr) minmax(390px,.68fr);align-items:center;gap:84px}.action{justify-self:end;width:100%}}
    @media(prefers-color-scheme:dark){:root{color-scheme:dark;--bg:#101512;--fg:#f1f5f2;--muted:#9eaaa3;--line:rgba(244,248,245,.12);--primary:#62d5aa;--soft:#193328}.action button{color:#0a1913}}
    @media(max-width:420px){.stage{padding:16px}.wrap{min-height:calc(100dvh - 32px)}.content{padding:34px 0}.lead h1{font-size:38px}.lead p{font-size:14px}.foot span:last-child{display:none}}
  `}</style></head><body><main className="stage" role="alert" aria-live="assertive"><div className="wrap"><header className="brand"><span className="mark" aria-hidden="true"><i /></span>Moneva</header><div className="content"><section className="lead"><p className="eyebrow">Interrupción temporal</p><h1>La aplicación necesita volver a cargar.</h1><p>Algo detuvo esta pantalla antes de terminar. Tus datos ya guardados permanecen protegidos y Moneva no los reemplazó con información incompleta.</p></section><section className="action" aria-label="Recuperar la aplicación"><h2>Intenta abrir Moneva otra vez</h2><p>Volveremos a solicitar la pantalla y sus datos. Si la interrupción continúa, revisa la conexión antes de repetir.</p><button type="button" onClick={retry}>Volver a intentar</button>{error.digest ? <p className="ref">Referencia técnica: {error.digest}</p> : null}</section></div><footer className="foot"><span>Moneva · claridad para decidir</span><span>Sin cambios silenciosos</span></footer></div></main></body></html>;
}
