"use client";

import Link from "next/link";
import { ArrowRight, BellRing, CalendarClock, ChevronRight, CircleAlert, CircleCheck, Flag, Search, SlidersHorizontal } from "lucide-react";
import { useFinance } from "@/components/finance-provider";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { accountBaseBalance, currencyFormatter, groupBudgetSummary, localIsoDate, monthLabel, monthTotals } from "@/lib/finance/calculations";
import { availableTone, budgetUsageTone, expenseTone, financialToneClass, type FinancialTone } from "@/lib/finance/financial-status";
import { financialTargetProgress } from "@/lib/finance/financial-targets";
import { FinanceIcon } from "@/lib/finance/icon-catalog";
import { movementIdentityTone } from "@/lib/finance/movement-visuals";
import { budgetsWithRecurringCommitments, recurringCommitmentsByCategory } from "@/lib/finance/recurrence";
import type { RecurringOccurrence, Transaction } from "@/lib/finance/types";
import { cn } from "@/lib/utils";

export function DashboardPage() {
  const { profile, accounts, transactions, recurringRules, recurringOccurrences, financialTargets, financialTargetEntries, categories, budgets, groupAllocations, snapshot, currentMonth, pendingCount, syncError } = useFinance();
  const money = currencyFormatter(profile?.currencyCode);
  const totals = monthTotals(transactions, currentMonth, snapshot);
  const available = totals.income - totals.expense;
  const netWorth = snapshot?.netWorth ?? accounts.filter((account) => !account.archived).reduce((sum, account) => sum + accountBaseBalance(account, transactions, snapshot), 0);
  const today = localIsoDate(new Date(), profile?.timezone);
  const plannedThisMonth = recurringOccurrences.filter((item) => item.status === "planned" && item.effectiveOn >= today && item.effectiveOn.slice(0, 7) === currentMonth.slice(0, 7));
  const plannedExpense = plannedThisMonth.filter((item) => item.kind === "expense").reduce((sum, item) => sum + item.amount, 0);
  const plannedIncome = plannedThisMonth.filter((item) => item.kind === "income").reduce((sum, item) => sum + item.amount, 0);
  const projectedClose = available + plannedIncome - plannedExpense;
  const commitments = recurringCommitmentsByCategory(recurringOccurrences, recurringRules, currentMonth);
  const effectiveBudgets = budgetsWithRecurringCommitments(budgets, commitments, currentMonth);
  const groups = groupBudgetSummary(categories, effectiveBudgets, transactions, groupAllocations, currentMonth, snapshot);
  const recent = transactions.filter((transaction) => transaction.kind !== "transfer_in" && !transaction.kind.startsWith("adjustment")).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, 5);
  const availablePercent = Math.round((available / Math.max(totals.income, 1)) * 100);
  const boundedAvailablePercent = Math.max(0, Math.min(100, availablePercent));
  const availableSignal = availableTone(available);
  const netWorthSignal = availableTone(netWorth);
  const hasPlanning = groupAllocations.some((group) => !group.archived && group.includedInPlan) || groups.some((group) => group.budget > 0);
  const [currentYear, currentMonthNumber] = currentMonth.split("-").map(Number);
  const currentDay = Number(today.slice(8, 10));
  const daysInMonth = new Date(Date.UTC(currentYear, currentMonthNumber, 0)).getUTCDate();
  const daysRemaining = Math.max(0, daysInMonth - currentDay);
  const fullMonth = monthLabel(currentMonth);
  const upcoming = plannedThisMonth.filter((item) => dayDistance(today, item.effectiveOn) <= 7).sort((a, b) => a.effectiveOn.localeCompare(b.effectiveOn)).slice(0, 4);
  const alerts = buildAlerts({ groups, recurringOccurrences, today, projectedClose, money, pendingCount, syncError }).slice(0, 3);
  const activeTargets = financialTargets.filter((target) => target.status === "active").sort((a, b) => a.priority - b.priority || b.updatedAt.localeCompare(a.updatedAt)).slice(0, 3);

  return <div className="min-w-0" data-dashboard>
    <section className="min-w-0 pb-8 md:border-b md:border-border/75 lg:pb-10" data-dashboard-hero>
      <div className="max-w-[44rem]"><p className="mb-2 text-sm text-muted-foreground">Hola, {profile?.displayName.split(" ")[0] || "hola"} <span aria-hidden="true">👋</span></p><h1 className="text-balance text-[clamp(2rem,4vw,3.5rem)] font-medium leading-[1.02] tracking-[-0.06em]">Tu mes, de un vistazo.</h1><p className="mt-3 max-w-xl text-pretty text-sm leading-6 text-muted-foreground">{daysRemaining === 0 ? `${fullMonth} termina hoy.` : `Te ${daysRemaining === 1 ? "queda" : "quedan"} ${daysRemaining} ${daysRemaining === 1 ? "día" : "días"} para cerrar ${fullMonth}.`} Lo real ya ocurrió; lo previsto todavía puede cambiar tu cierre.</p></div>
      <div className="mt-8 grid min-w-0 gap-y-7 sm:mt-10 lg:grid-cols-[minmax(320px,1.35fr)_minmax(0,1fr)] lg:gap-x-12">
        <div className="min-w-0 [container-type:inline-size]"><p className="text-xs text-muted-foreground">Patrimonio disponible</p><p data-dashboard-balance className={cn("mt-1 whitespace-nowrap text-[clamp(1.75rem,10cqi,4.8rem)] font-medium leading-none tracking-[-0.055em] tabular-nums", financialToneClass[netWorthSignal])}>{money.format(netWorth)}</p><div className={cn("mt-6 grid min-w-0 grid-cols-[minmax(7rem,1fr)_auto] items-center gap-4 text-xs", financialToneClass[availableSignal])}>{totals.income > 0 ? <><span className={cn("h-2 w-full overflow-hidden rounded-full", available > 0 ? "bg-positive/15" : "bg-destructive/15")} role="progressbar" aria-label="Porcentaje del ingreso mensual disponible" aria-valuemin={0} aria-valuemax={100} aria-valuenow={boundedAvailablePercent}><span className={cn("block h-full rounded-full", available > 0 ? "bg-positive" : "bg-destructive")} style={{ width: `${boundedAvailablePercent}%` }} /></span><span className="text-right tabular-nums">{available > 0 ? `${availablePercent}% del ingreso libre` : available === 0 ? "Ingreso consumido" : "Por cubrir"}</span></> : <p className="col-span-2 max-w-lg leading-5 text-muted-foreground">Tu saldo inicial ya forma parte del patrimonio. Cuando llegue el primer ingreso, aquí verás el margen del mes.</p>}</div></div>
        <div className="grid grid-cols-2 gap-px overflow-hidden border-y bg-border sm:grid-cols-4 lg:grid-cols-2"><Metric label="Ingresado" value={money.format(totals.income)} tone={availableTone(totals.income)} /><Metric label="Gastado" value={money.format(totals.expense)} tone={expenseTone(totals.expense)} /><Metric label="Comprometido" value={money.format(plannedExpense)} tone={plannedExpense > 0 ? "warning" : "neutral"} /><Metric label="Cierre proyectado" value={money.format(projectedClose)} tone={availableTone(projectedClose)} /></div>
      </div>
    </section>

    <section className="grid min-w-0 gap-9 py-8 lg:py-10 xl:grid-cols-[minmax(0,1.38fr)_minmax(320px,.62fr)] xl:gap-12">
      <div className="min-w-0" data-dashboard-budget>
        <div className="mb-5 flex items-end justify-between"><div><p className="text-[11px] font-medium uppercase tracking-[.14em] text-primary">Plan en marcha</p><h2 className="mt-2 text-xl font-medium tracking-[-.025em]">Presupuesto por categoría</h2><p className="mt-1 text-sm text-muted-foreground">{money.format(groups.reduce((sum, group) => sum + group.spent, 0))} usados · {money.format(plannedExpense)} previstos</p></div><Link href="/presupuestos?vista=presupuesto" className="hidden items-center gap-1 text-xs font-medium text-primary sm:flex">Ver todo <ChevronRight className="size-3.5" /></Link></div>
        {hasPlanning ? <div className="divide-y">{groups.slice().sort((a, b) => b.percent - a.percent).slice(0, 4).map((group) => <CategoryRow key={group.group} {...group} icon={groupAllocations.find((item) => item.group === group.group)?.icon ?? "tag"} money={money} />)}</div> : <div className="border-y py-7"><p className="text-sm font-medium">El plan es opcional</p><p className="mt-1 max-w-xl text-sm leading-6 text-muted-foreground">Tus cuentas y movimientos funcionan sin porcentajes ni presupuestos. Actívalos solo si quieres medir límites.</p><Button asChild variant="outline" size="sm" className="mt-4 rounded-full"><Link href="/presupuestos?vista=distribucion">Configurar plan</Link></Button></div>}
      </div>
      <aside className="min-w-0 xl:border-l xl:pl-9" data-dashboard-pulse>
        <div className="flex items-center justify-between"><div><p className="text-[11px] font-medium uppercase tracking-[.14em] text-primary">Atención</p><h2 className="mt-2 text-xl font-medium tracking-[-.025em]">Lo que merece una mirada</h2></div>{alerts.length ? <BellRing className="size-5 text-warning" /> : <CircleCheck className="size-5 text-positive" />}</div>
        <div className="mt-4 divide-y">{alerts.length ? alerts.map((alert) => <Link key={alert.id} href={alert.href} className="grid min-h-[72px] grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 py-3"><span className={cn("grid size-9 place-items-center rounded-xl", alert.tone === "destructive" ? "bg-destructive/10 text-destructive" : "bg-warning/12 text-warning")}><CircleAlert className="size-4" /></span><span className="min-w-0"><span className="block text-sm font-medium">{alert.title}</span><span className="mt-1 block truncate text-xs text-muted-foreground">{alert.detail}</span></span><ChevronRight className="size-4 text-muted-foreground" /></Link>) : <div className="py-8"><p className="text-sm font-medium text-positive">Todo en orden por ahora</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Moneva te avisará aquí si un presupuesto se acerca al límite o una programación falla.</p></div>}</div>
      </aside>
    </section>

    <section className="border-t py-8" aria-labelledby="dashboard-targets-title" data-dashboard-targets><div className="mb-4 flex items-end justify-between gap-4"><div><p className="text-[11px] font-medium uppercase tracking-[.14em] text-primary">En camino</p><h2 id="dashboard-targets-title" className="mt-2 text-xl font-medium tracking-[-.025em]">Metas y deudas</h2><p className="mt-1 text-sm text-muted-foreground">El próximo destino de tu dinero, con avance verificable.</p></div><Link href="/metas" className="flex min-h-11 shrink-0 items-center gap-1 px-2 text-xs font-medium text-primary">Ver todas <ChevronRight className="size-3.5" /></Link></div><div className={cn("grid min-w-0", activeTargets.length === 2 && "gap-x-8 lg:grid-cols-2", activeTargets.length >= 3 && "gap-x-8 lg:grid-cols-2 lg:[&>*:last-child]:col-span-2 2xl:grid-cols-3 2xl:[&>*:last-child]:col-span-1")}>{activeTargets.length ? activeTargets.map((target, index) => { const progress = financialTargetProgress(target, financialTargetEntries, transactions); return <DashboardTargetRow key={target.id} target={target} progress={progress} money={money} compact={activeTargets.length > 1} separated={index > 0} />; }) : <Link href="/metas?meta=nueva" className="flex min-h-20 items-center justify-center gap-2 py-4 text-sm text-muted-foreground hover:text-primary"><Flag className="size-4" />Crear tu primer recorrido</Link>}</div></section>

    <section className="grid gap-9 border-t py-8 lg:grid-cols-[minmax(0,1fr)_minmax(300px,.55fr)] lg:gap-12">
      <div className="min-w-0"><div className="mb-4 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-medium tracking-[-.025em]">Últimos movimientos</h2><p className="mt-1 text-sm text-muted-foreground">Lo que ya ocurrió y afecta tus saldos.</p></div><div className="flex gap-2"><Button asChild variant="outline" size="sm" className="rounded-full"><Link href="/movimientos#movement-history-filters"><Search className="size-4" />Buscar</Link></Button><Button asChild variant="outline" size="sm" className="rounded-full"><Link href="/movimientos#movement-history-filters"><SlidersHorizontal className="size-4" />Filtrar</Link></Button></div></div><div className="divide-y">{recent.length ? recent.map((transaction) => { const category = categories.find((item) => item.id === transaction.categoryId); const account = accounts.find((item) => item.id === transaction.accountId); return <TransactionRow key={transaction.id} transaction={transaction} category={category?.name} icon={transaction.icon ?? category?.icon ?? (transaction.kind.startsWith("transfer") ? "hand-coins" : transaction.kind === "income" ? "coins" : "receipt")} nativeMoney={currencyFormatter(transaction.nativeCurrencyCode ?? account?.currencyCode ?? profile?.currencyCode)} reportMoney={money} />; }) : <Empty text="Cuando registres el primer movimiento aparecerá aquí." />}</div></div>
      <aside><div className="mb-4 flex items-end justify-between"><div><h2 className="text-xl font-medium tracking-[-.025em]">Próximos 7 días</h2><p className="mt-1 text-sm text-muted-foreground">Cobros e ingresos previstos.</p></div><Link href="/movimientos?vista=calendario" aria-label="Abrir calendario" className="grid size-11 shrink-0 place-items-center rounded-xl text-primary transition-colors duration-[var(--motion-duration-state)] ease-[var(--motion-ease-out)] hover:bg-secondary focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary"><ArrowRight className="size-5" /></Link></div><div className="divide-y">{upcoming.length ? upcoming.map((item) => <UpcomingRow key={item.id} occurrence={item} money={money} />) : <Empty text="No hay movimientos programados para esta semana." />}</div></aside>
    </section>
  </div>;
}

function Metric({ label, value, tone }: { label: string; value: string; tone: FinancialTone }) { return <div className="min-w-0 bg-background px-3 py-5 sm:px-4"><p className="text-[11px] text-muted-foreground">{label}</p><p className={cn("mt-2 whitespace-nowrap text-[clamp(.75rem,4vw,1.125rem)] font-medium tracking-[-.045em] tabular-nums sm:text-lg", financialToneClass[tone])}>{value}</p></div>; }
function DashboardTargetRow({ target, progress, money, compact, separated }: { target: ReturnType<typeof useFinance>["financialTargets"][number]; progress: ReturnType<typeof financialTargetProgress>; money: Intl.NumberFormat; compact: boolean; separated: boolean }) { const percent = Math.round(progress.percent); return <Link href={`/metas?meta=${encodeURIComponent(target.id)}`} data-dashboard-target className={cn("group grid min-h-[92px] min-w-0 grid-cols-[auto_minmax(0,1fr)] items-center gap-3 rounded-xl py-4 outline-none transition-colors duration-[var(--motion-duration-state)] ease-[var(--motion-ease-out)] hover:bg-secondary/30 focus-visible:ring-2 focus-visible:ring-ring sm:gap-4", compact ? "px-2" : "sm:min-h-[112px] sm:grid-cols-[auto_minmax(0,1fr)] sm:px-3", separated && "border-t border-border/65 lg:border-t-0", compact && separated && "lg:border-t-0", compact && "lg:[&:nth-child(n+3)]:border-t lg:[&:nth-child(n+3)]:border-border/65 2xl:border-t-0 2xl:[&:nth-child(n+3)]:border-t-0")}><span className={cn("grid shrink-0 place-items-center rounded-2xl transition-transform duration-[var(--motion-duration-press)] ease-[var(--motion-ease-out)] group-active:scale-[var(--motion-press-scale)] motion-reduce:transition-none motion-reduce:group-active:scale-100", compact ? "size-11" : "size-12 sm:size-14")} style={{ color: target.color, backgroundColor: `${target.color}16` }}><FinanceIcon name={target.icon} className={compact ? "size-[19px]" : "size-5 sm:size-6"} /></span><span className="min-w-0"><span className="flex min-w-0 items-baseline justify-between gap-4"><span className={cn("truncate font-medium tracking-[-.015em]", compact ? "text-sm" : "text-base sm:text-lg")}>{target.title}</span><span className="shrink-0 text-right"><span className={cn("block font-medium tabular-nums", compact ? "text-sm" : "text-base")}>{money.format(progress.remaining)}</span><span className="block text-[11px] text-muted-foreground">{target.mode === "pay_down" ? "por pagar" : "pendiente"}</span></span></span><span className="mt-3 grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3"><Progress className={compact ? "h-1.5" : "h-2"} indicatorClassName="bg-[var(--target-color)]" style={{ "--target-color": target.color } as React.CSSProperties} value={progress.rawProgress} max={target.targetAmount} label={`Avance de ${target.title}`} valueText={`${percent}% completado`} /><span className="min-w-8 text-right text-xs font-medium tabular-nums" style={{ color: target.color }}>{percent}%</span></span><span className="mt-2 flex items-center justify-between gap-3 text-[11px] text-muted-foreground"><span className="truncate tabular-nums">{money.format(progress.currentProgress)} acumulados</span><span className="shrink-0 tabular-nums">Meta {money.format(target.targetAmount)}</span></span></span></Link>; }
function CategoryRow({ name, color, budget, spent, percent, icon, money }: ReturnType<typeof groupBudgetSummary>[number] & { icon: string; money: Intl.NumberFormat }) { const tone = budgetUsageTone(spent, budget); const indicator = tone === "destructive" ? "var(--destructive)" : tone === "warning" ? "var(--warning)" : color; return <Link href="/presupuestos?vista=presupuesto" className="grid min-h-[72px] grid-cols-[minmax(0,1fr)_auto] items-center gap-3 py-3 sm:grid-cols-[180px_minmax(120px,1fr)_130px_auto] sm:gap-4"><span className="flex min-w-0 items-center gap-3 text-sm font-medium"><span className="grid size-9 shrink-0 place-items-center rounded-xl" style={{ color, backgroundColor: `${color}16` }}><FinanceIcon name={icon} className="size-[17px]" /></span><span className="truncate">{name}</span></span><span className="hidden h-1.5 overflow-hidden rounded-full bg-muted sm:block"><span className="block h-full rounded-full" style={{ width: `${Math.min(100, Math.max(0, percent))}%`, backgroundColor: indicator }} /></span><span className="text-right"><span className={cn("block text-sm font-medium tabular-nums", financialToneClass[tone])}>{money.format(spent)}</span><span className="text-[11px] text-muted-foreground">de {money.format(budget)}</span></span><span className={cn("hidden w-12 text-right text-xs tabular-nums sm:block", financialToneClass[tone])}>{percent}%</span></Link>; }
function TransactionRow({ transaction, category, icon, nativeMoney, reportMoney }: { transaction: Transaction; category?: string; icon: string; nativeMoney: Intl.NumberFormat; reportMoney: Intl.NumberFormat }) { const income = transaction.kind === "income" || transaction.kind === "transfer_in"; const tone = movementIdentityTone(transaction.kind); const title = transaction.merchant || transaction.description; const nativeCurrency = transaction.nativeCurrencyCode ?? "COP"; return <Link href={`/movimientos?overlay=movement&transaction=${encodeURIComponent(transaction.id)}`} data-dashboard-transaction data-transaction-id={transaction.id} aria-label={`Abrir detalles de ${title}`} className="group grid min-h-[66px] grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 rounded-xl py-2 outline-none transition-colors duration-[var(--motion-duration-state)] ease-[var(--motion-ease-out)] hover:bg-secondary/30 focus-visible:ring-2 focus-visible:ring-ring"><span className={cn("grid size-9 place-items-center rounded-full transition-transform duration-[var(--motion-duration-press)] ease-[var(--motion-ease-out)] group-active:scale-[var(--motion-press-scale)] motion-reduce:transition-none motion-reduce:group-active:scale-100", tone.surface, tone.text)}><FinanceIcon name={icon} className="size-[17px]" /></span><span className="min-w-0"><span className="block truncate text-sm font-medium group-hover:text-primary">{title}</span><span className="block truncate text-xs text-muted-foreground">{category || "Transferencia"} · {shortDate(transaction.occurredOn)}</span></span><span className="text-right"><span className={cn("block text-sm font-medium tabular-nums", tone.text)}>{income ? "+" : "−"}{nativeMoney.format(transaction.amount)}</span>{nativeCurrency !== "COP" ? <span className="block text-[10px] tabular-nums text-muted-foreground">≈ {reportMoney.format(transaction.baseAmount ?? transaction.amount)}</span> : null}</span></Link>; }
function UpcomingRow({ occurrence, money }: { occurrence: RecurringOccurrence; money: Intl.NumberFormat }) { const positive = occurrence.kind === "income"; return <Link href="/movimientos?vista=calendario" className="grid min-h-[66px] grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 py-2"><span className={cn("grid size-9 place-items-center rounded-xl", positive ? "bg-positive/12 text-positive" : "bg-warning/12 text-warning")}><CalendarClock className="size-4" /></span><span className="min-w-0"><span className="block truncate text-sm font-medium">{occurrence.description}</span><span className="block text-xs text-muted-foreground">{shortDate(occurrence.effectiveOn)} · previsto</span></span><span className={cn("text-sm font-medium tabular-nums", positive ? "text-positive" : "text-warning")}>{positive ? "+" : "−"}{money.format(occurrence.amount)}</span></Link>; }
function Empty({ text }: { text: string }) { return <p className="py-7 text-sm leading-6 text-muted-foreground">{text}</p>; }
function shortDate(value: string) { return new Intl.DateTimeFormat("es-CO", { day: "numeric", month: "short", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)).replace(" de ", " "); }
function dayDistance(from: string, to: string) { return Math.max(0, Math.round((new Date(`${to}T00:00:00Z`).getTime() - new Date(`${from}T00:00:00Z`).getTime()) / 86_400_000)); }
function buildAlerts({ groups, recurringOccurrences, today, projectedClose, money, pendingCount, syncError }: { groups: ReturnType<typeof groupBudgetSummary>; recurringOccurrences: RecurringOccurrence[]; today: string; projectedClose: number; money: Intl.NumberFormat; pendingCount: number; syncError: string | null }) { const alerts: Array<{ id: string; title: string; detail: string; href: string; tone: "warning" | "destructive" }> = []; const over = groups.find((group) => group.percent > 100); const near = groups.find((group) => group.percent >= 80 && group.percent <= 100); const failed = recurringOccurrences.find((item) => item.status === "failed"); const soon = recurringOccurrences.filter((item) => item.status === "planned" && item.effectiveOn >= today && dayDistance(today, item.effectiveOn) <= 3).sort((a, b) => a.effectiveOn.localeCompare(b.effectiveOn))[0]; if (syncError) alerts.push({ id: "sync", title: "Sincronización por revisar", detail: syncError, href: "/ajustes", tone: "destructive" }); else if (pendingCount) alerts.push({ id: "pending", title: `${pendingCount} cambios pendientes`, detail: "Tus datos están seguros en este dispositivo.", href: "/ajustes", tone: "warning" }); if (failed) alerts.push({ id: `failed-${failed.id}`, title: "Una programación falló", detail: failed.description, href: "/movimientos?vista=programados", tone: "destructive" }); if (over) alerts.push({ id: `over-${over.group}`, title: `${over.name} superó el límite`, detail: `${over.percent}% del presupuesto usado`, href: "/presupuestos?vista=presupuesto", tone: "destructive" }); else if (near) alerts.push({ id: `near-${near.group}`, title: `${near.name} está cerca del límite`, detail: `${near.percent}% del presupuesto usado`, href: "/presupuestos?vista=presupuesto", tone: "warning" }); if (projectedClose < 0) alerts.push({ id: "projection", title: "El cierre proyectado es negativo", detail: `${money.format(Math.abs(projectedClose))} por cubrir`, href: "/movimientos?vista=calendario", tone: "destructive" }); if (soon) alerts.push({ id: `soon-${soon.id}`, title: `${soon.description} se acerca`, detail: `${shortDate(soon.effectiveOn)} · ${money.format(soon.amount)}`, href: "/movimientos?vista=calendario", tone: "warning" }); return alerts; }
